### PR TITLE
symfony version in composer.json updated

### PR DESCRIPTION
**Pull request by ruslan-polutsygan**

### CODE REVIEW

**Comment by 66Ton99** [comment]
Unfortunately it require much more work to update it for Symfony 3.0

**Comment by ruslan-polutsygan** [comment]
Hi 

I've updated service configuration files -  changed `scope="prototype"` to `shared="false"`.
But this works only for symfony version since 2.8 - http://symfony.com/doc/master/cookbook/service_container/shared.html
I can add compiler pass which would either set scope or share based on detected symfony version.
Will this work for you?

**Comment by ruslan-polutsygan** [comment]
Are there any other problems with using the bundle with symfony 3.0?

**Comment by 66Ton99** [comment]
Yes, it is need new version of Mink 
https://travis-ci.org/minkphp/MinkBundle/jobs/107401664

**Comment by ruslan-polutsygan** [comment]
ping

**Comment by 66Ton99** [comment]
Did you try to install all dependencies?
Looks like some dependencies incompatible with SF3.0 https://travis-ci.org/minkphp/MinkBundle/jobs/107429370

**Comment by ruslan-polutsygan** [comment]
Yes, I just had to say explicitly `"behat/mink": "dev-master"` in composer.json

**Comment by ruslan-polutsygan** [comment]
ping

**Comment by 66Ton99** [comment]
I need to finish #66 first!

**Comment by ruslan-polutsygan** [comment]
great. thx.

**Pull request closed without merging**
