### PR TITLE
Added all drivers but Zombie have a bug

### PR DESCRIPTION
**Pull request by 66Ton99**

### CODE REVIEW

**Comment by robertfausk** [comment]
Will there be any progress on this task?

**Comment by 66Ton99** [comment]
It is already merged

**Comment by robertfausk** [comment]
Ok, sorry for misunderstanding.

I meant what's the bug of zombie driver? How does he show up? Is zombie driver unusable?

**Comment by stof** [comment]
@robertfausk I have no idea. I don't know what `has a bug` is. This is not a bug report. If ZombieDriver does not work, create an issue sayign what does not work

**Pull request merged**
